export const ETHIOPIAN_CITIES = [
  'Addis Ababa',
  'Dire Dawa',
  'Mekelle',
  'Gondar',
  'Bahir Dar',
  'Hawassa',
  'Adama',
  'Jimma',
  'Dessie',
  'Jijiga',
  'Shashamane',
  'Bishoftu',
  'Arba Minch',
  'Hosaena',
  'Harar',
  'Dilla',
  'Nekemte',
  'Debre Birhan',
  'Asella',
  'Debre Markos',
  'Kombolcha',
  'Debre Tabor',
  'Sodo',
  'Adigrat',
  'Ambo',
  'Axum',
  'Gambela',
  'Asosa',
  'Semera',
  'Woldiya',
] as const

export type EthiopianCity = (typeof ETHIOPIAN_CITIES)[number]
